## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])

application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [4]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
application_count = application_df['APPLICATION_TYPE'].value_counts()

application_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_count[application_count < 250].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
application_classification = application_df['CLASSIFICATION'].value_counts()
application_classification

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_classification_count = application_classification[application_classification >1]

application_classification_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(application_classification[application_classification < 800].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)

application_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [11]:
# Split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"].values
X = application_df.drop(["IS_SUCCESSFUL"],axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [25]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  150
hidden_nodes_layer2 = 150

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 250)               11000

 dense_13 (Dense)            (None, 150)               37650

 dense_14 (Dense)            (None, 1)                 151

=================================================================
Total params: 48801 (190.63 KB)
Trainable params: 48801 (190.63 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [26]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [27]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=75)

Epoch 1/75
804/804 [==============================] - 4s 3ms/step - loss: 0.5683 - accuracy: 0.7222
Epoch 2/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5562 - accuracy: 0.7290
Epoch 3/75
804/804 [==============================] - 3s 4ms/step - loss: 0.5527 - accuracy: 0.7314
Epoch 4/75
804/804 [==============================] - 3s 4ms/step - loss: 0.5508 - accuracy: 0.7301
Epoch 5/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5499 - accuracy: 0.7325
Epoch 6/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5485 - accuracy: 0.7326
Epoch 7/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5483 - accuracy: 0.7333
Epoch 8/75
804/804 [==============================] - 4s 5ms/step - loss: 0.5470 - accuracy: 0.7332
Epoch 9/75
804/804 [==============================] - 4s 5ms/step - loss: 0.5468 - accuracy: 0.7332
Epoch 10/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5463 - accuracy: 0.7340
Epoch 11/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5457 - accuracy: 0.7345
Epoch 12/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5447 - accuracy: 0.7341
Epoch 13/75
804/804 [==============================] - 4s 5ms/step - loss: 0.5441 - accuracy: 0.7353
Epoch 14/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5440 - accuracy: 0.7350
Epoch 15/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5438 - accuracy: 0.7357
Epoch 16/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5434 - accuracy: 0.7361
Epoch 17/75
804/804 [==============================] - 4s 4ms/step - loss: 0.5433 - accuracy: 0.7355
Epoch 18/75
804/804 [==============================] - 4s 4ms/step - loss: 0.5430 - accuracy: 0.7370
Epoch 19/75
804/804 [==============================] - 3s 4ms/step - loss: 0.5426 - accuracy: 0.7360
Epoch 20/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5420 - accuracy: 0.7363
Epoch 21/75
804/804 [==============================] - 3s 4ms/step - loss: 0.5418 - accuracy: 0.7369
Epoch 22/75
804/804 [==============================] - 4s 4ms/step - loss: 0.5419 - accuracy: 0.7364
Epoch 23/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5415 - accuracy: 0.7366
Epoch 24/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5414 - accuracy: 0.7365
Epoch 25/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5414 - accuracy: 0.7365
Epoch 26/75
804/804 [==============================] - 3s 4ms/step - loss: 0.5405 - accuracy: 0.7373
Epoch 27/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5412 - accuracy: 0.7379
Epoch 28/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5402 - accuracy: 0.7381
Epoch 29/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7383
Epoch 30/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5399 - accuracy: 0.7382
Epoch 31/75
804/804 [==============================] - 3s 4ms/step - loss: 0.5395 - accuracy: 0.7381
Epoch 32/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5395 - accuracy: 0.7378
Epoch 33/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7381
Epoch 34/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5390 - accuracy: 0.7384
Epoch 35/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5387 - accuracy: 0.7383
Epoch 36/75
804/804 [==============================] - 4s 5ms/step - loss: 0.5393 - accuracy: 0.7380
Epoch 37/75
804/804 [==============================] - 5s 6ms/step - loss: 0.5382 - accuracy: 0.7379
Epoch 38/75
804/804 [==============================] - 4s 4ms/step - loss: 0.5382 - accuracy: 0.7388
Epoch 39/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5379 - accuracy: 0.7390
Epoch 40/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5379 - accuracy: 0.7390
Epoch 41/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5378 - accuracy: 0.7391
Epoch 42/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5378 - accuracy: 0.7384
Epoch 43/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7399
Epoch 44/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5372 - accuracy: 0.7388
Epoch 45/75
804/804 [==============================] - 3s 4ms/step - loss: 0.5375 - accuracy: 0.7383
Epoch 46/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5368 - accuracy: 0.7389
Epoch 47/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5366 - accuracy: 0.7386
Epoch 48/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5376 - accuracy: 0.7389
Epoch 49/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5372 - accuracy: 0.7392
Epoch 50/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.7394
Epoch 51/75
804/804 [==============================] - 3s 4ms/step - loss: 0.5369 - accuracy: 0.7393
Epoch 52/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5371 - accuracy: 0.7388
Epoch 53/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5365 - accuracy: 0.7399
Epoch 54/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.7391
Epoch 55/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5366 - accuracy: 0.7400
Epoch 56/75
804/804 [==============================] - 3s 4ms/step - loss: 0.5364 - accuracy: 0.7406
Epoch 57/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7394
Epoch 58/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7388
Epoch 59/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7402
Epoch 60/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7397
Epoch 61/75
804/804 [==============================] - 3s 4ms/step - loss: 0.5356 - accuracy: 0.7393
Epoch 62/75
804/804 [==============================] - 4s 5ms/step - loss: 0.5355 - accuracy: 0.7397
Epoch 63/75
804/804 [==============================] - 6s 7ms/step - loss: 0.5354 - accuracy: 0.7394
Epoch 64/75
804/804 [==============================] - 6s 8ms/step - loss: 0.5357 - accuracy: 0.7399
Epoch 65/75
804/804 [==============================] - 4s 5ms/step - loss: 0.5357 - accuracy: 0.7398
Epoch 66/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5354 - accuracy: 0.7398
Epoch 67/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5362 - accuracy: 0.7400
Epoch 68/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5374 - accuracy: 0.7397
Epoch 69/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5355 - accuracy: 0.7394
Epoch 70/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7400
Epoch 71/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5348 - accuracy: 0.7396
Epoch 72/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5350 - accuracy: 0.7398
Epoch 73/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5382 - accuracy: 0.7390
Epoch 74/75
804/804 [==============================] - 3s 4ms/step - loss: 0.5341 - accuracy: 0.7405
Epoch 75/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5341 - accuracy: 0.7398

In [28]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5651 - accuracy: 0.7290 - 554ms/epoch - 2ms/step
Loss: 0.5650903582572937, Accuracy: 0.7289795875549316

In [30]:
# Export our model to HDF5 file
from google.colab import files
nn.save('/content/AlphabetSoupCharity_Optimization.h5')
files.download('AlphabetSoupCharity_Optimization.h5')